### ISSUE TITLE
Login & Register Pages - Styling & Navigation

### ISSUE THREAD

**Issue by TheBMPatil** [AjayPalhal-1/attendance-frontend#2]
**Description:**  
The login and registration pages are not properly styled, and they are not interconnected.

**Expected Behavior:**  
1. **Login Page:** Add a link to navigate to the registration page.  
2. **Register Page:** Add a link to navigate back to the login page.  
3. **Styling:** Ensure consistent and proper styling across both pages.  
4. **IDs:** All components should have unique IDs for better structure.

**Expected Behavior:**

**Login Page:** There should be an option on the login page to navigate to the registration page (e.g., "Don't have an account? Register").
**Registration Page:** There should be an option on the registration page to navigate back to the login page (e.g., "Already have an account? Login").
**Consistent Styling:** All pages should have consistent styling that aligns with the design guidelines.
**Unique Component IDs:** All components should have unique IDs for easy manipulation and styling.

**Comment by AjayPalhal-1** [comment]
@ankushp9  has Did This Changes

@TheBMPatil Pls Check
